site_name: weaver
repo_url: https://github.com/gregoryhunt/weaver
site_url: https://gregoryhunt.github.io/weaver
site_description: A new type of interface engine
site_author: Gregory Hunt
edit_uri: edit/main/docs/
repo_name: gregoryhunt/weaver
copyright: Maintained by <a href="https://gregoryhunt.com">gregoryhunt</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/weaver"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gregoryhunt/weaver
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/weaver

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
